const GET_FEEDBACK_LIST = 'GET_FEEDBACK_LIST';
const SET_FEEDBACK_LIST = 'SET_FEEDBACK_LIST';
const GET_FEEDBACK_LIST_ERROR = 'GET_FEEDBACK_LIST_ERROR';

export {
  GET_FEEDBACK_LIST,
  SET_FEEDBACK_LIST,
  GET_FEEDBACK_LIST_ERROR
}